### ISSUE TITLE
Error when applying biome color with BetterFoliage

### ISSUE THREAD

**Issue by ghost** [Cadiboo/RenderChunk-rebuildChunk-Hooks#3]
I got this error when I try to apply a server resource pack.

```
java.lang.ArrayIndexOutOfBoundsException: 44596
	at net.minecraft.world.ColorizerFoliage.func_77470_a(SourceFile:14)
	at net.minecraft.world.biome.Biome.func_180625_c(Biome.java:331)
	at net.minecraft.world.biome.BiomeColorHelper$2.func_180283_a(SourceFile:20)
	at net.minecraft.world.biome.BiomeColorHelper.func_180285_a(SourceFile:36)
	at net.minecraft.world.biome.BiomeColorHelper.func_180287_b(SourceFile:51)
	at net.minecraft.client.renderer.color.BlockColors$4.func_186720_a(BlockColors.java:92)
	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:185)
	at mods.octarinecore.client.render.BlockContext.blockData(AbstractBlockRenderingHandler.kt:84)
	at mods.betterfoliage.client.integration.OptifineCTM.getBlockColor(OptifineCTM.kt:96)
	at mods.betterfoliage.client.render.RenderLeaves.render(RenderLeaves.kt:61)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:89)
	at cadiboo.renderchunkrebuildchunkhooks.mod.BetterFoliageCompatibilityEventSubscriber.callBetterFoliageHooks_renderWorldBlock_onRebuildChunkBlockEvent(BetterFoliageCompatibilityEventSubscriber.java:26)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_BetterFoliageCompatibilityEventSubscriber_callBetterFoliageHooks_renderWorldBlock_onRebuildChunkBlockEvent_RebuildChunkBlockEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at cadiboo.renderchunkrebuildchunkhooks.hooks.RenderChunkRebuildChunkHooksHooksOptifine.onRebuildChunkBlockEvent(RenderChunkRebuildChunkHooksHooksOptifine.java:170)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Cadiboo** [comment]
Can you reproduce this without this mod installed? It seems to be something deep in Better Foliage that’s going wrong. We just wrap their stuff to make it compatible with our event-driven approach, we don’t actually touch any of their code.

**Comment by Cadiboo** [comment]
Can you reproduce it with out the mod installed (only BetterFoliage/only vanilla)?

**Comment by Cadiboo** [comment]
Can you reproduce it with out the mod installed (only BetterFoliage/only vanilla)?

**Comment by Cadiboo** [comment]
Closed because of a lack of response, multiple updates and also this is for 1.12.2 and I'm now targeting 1.13.2
